name: Node.js Package

on:
  pull_request:
    branches:
      - master
      - github-actions
  push:
    branches:
      - master
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          echo -e "//npm.fury.io/licnz/:_authToken=${NODE_AUTH_TOKEN}\nalways-auth=true" > $RUNNER_TEMP/.npmrc
          cat $RUNNER_TEMP/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm ci
      - run: npm run build
      - run: npm publish --registry=https://npm.fury.io/licnz/
